# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache:
  packages: true

install:
  - R CMD build .
  - R CMD install nimbleEcology_0.1.0.tar.gz

# script:
  #- R CMD check nimbleEcology
  #- R CMD check nimbleEcology
