# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache:
  packages: true

install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  #- R CMD check nimbleEcology
  - R CMD build nimbleEcology
  #- R CMD check nimbleEcology
