# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os: osx

notifications:
  email:
    recipients:
      - dochvam@gmail.com
    on_success: always
    on_failure: always

branches:
  only:
    - master

install:
  - R CMD build nimbleEcology
  - R CMD INSTALL nimbleEcology

