# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - 3.5

cache:
  packages: true

notifications:
  email:
    recipients:
      - ben.goldstein@berkeley.edu
    on_success: change
    on_failure: change

script:
  - R CMD build .
  - R CMD check . --as-cran
  - R CMD INSTALL . --install-tests
  - Rscript ./run_tests.R
