# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - 3.5

cache:
  packages: true

notifications:
  email:
    recipients:
      - ben.goldstein@berkeley.edu
    on_success: always
    on_failure: always

script:
  - run_tests.R
